- name: "Add asdf Elixir plugin"
  ansible.builtin.shell: asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  
- name: "Install Elixir globally"
  ansible.builtin.shell: asdf install elixir {{ELIXIR_VERSION}}

- name: "Set Elixir version globally"
  ansible.builtin.shell: asdf global elixir {{ELIXIR_VERSION}}