---
# vars file for install-homebrew
install_homebrew_if_missing: true
upgrade_homebrew_packages: false

brew_cask_packages:
  # - atom
  # - docker
  # - dropbox
  # - firefox
  - google-chrome
  # - google-drive
  # - google-hangouts
  - iterm2
  # - keepassx
  # - kodi
  # - lastpass
  # - macvim
  # - royal-tsx
  # - skype
  # - slack
  # - sling
  # - spotify
  # - sublime-text
  # - vagrant
  # - vagrant-manager
  # - virtualbox
  # - virtualbox-extension-pack
  # - visual-studio-code
  # - vmware-fusion
brew_packages:
  # - autoconf
  # - bash-completion
  # - boot2docker
  # - consul
  # - docker-compose
  # - docker-machine
  # - doxygen
  # - git
  # - git-lfs
  # - go
  # - jq
  # - nmap
  # - nomad
  # - openssl
  # - packer
  # - pyenv
  # - python
  # - rancher-compose
  # - rbenv
  # - ruby-build
  # - ssh-copy-id
  # - terraform
  # - terraform-inventory
  # - terraform-provisioner-ansible
  # - tmux
  # - tree
  # - vault
  # - wget
  - yarn
  # - zsh
  # - zsh-syntax-highlighting